### ISSUE TITLE
Failing to access Storage Account - Container

### ISSUE THREAD

**Issue by Subhankar131** [borkod/Azure-Key-Vault-Backup-Restore#1]
On storage Account Level - **Enabled for all network**
Container - **Public Access level.**

Error Message : 
Line |
  19 |  New-Item -ItemType Directory -Force -Path $tmpFolder | Out-Null
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path '/KeyVaultBackup' is denied.

Any assistance would be highly appreciated. Thank you.

**Comment by cveld** [comment]
I believe this operation is performed locally on your OS and not remotely on the storage container. Therefore you should select a `$tmpFolder` location where you have write access.
